language: node_js

node_js:
  - 0.10
  - 0.12

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run check-ci

  # Manually send coverage reports to coveralls.
  # - Aggregate client results
  # - Single server and func test results
  # TODO(21): Functional coverage
  - ls coverage/client/*/lcov.info coverage/server/{rest,unit}/lcov.info | cat
  - cat coverage/client/*/lcov.info coverage/server/{rest,unit}/lcov.info | ./node_modules/.bin/coveralls || echo "Coveralls upload failed"

  # Prune deps to just production and ensure we can still build
  - npm prune --production
  - npm install --production
  - npm run build
